<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{{ $curricula->name }} Curriculum Summary</title>
<style>
body{font-family:Arial,sans-serif;color:#152d45;margin:28px}h1{font-size:22px;margin:0}p{margin:5px 0 22px;color:#53677b}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{border:2px solid #183449;display:flex;flex-direction:column;min-height:340px;break-inside:avoid}.card h2{font-size:14px;margin:0;padding:9px 11px;border-bottom:2px solid #183449;text-align:center}.card .meta{font-size:11px;padding:6px 11px;background:#f4f7f8;border-bottom:1px solid #183449}.card table{width:100%;border-collapse:collapse;font-size:11px}.card th,.card td{border:1px solid #183449;padding:6px;text-align:left}.card th{font-size:10px;text-transform:uppercase;background:#fafafa}.card td:last-child,.card th:last-child{text-align:center;width:70px}.empty{padding:18px;text-align:center;color:#667788;font-size:12px}@media print{body{margin:12mm}.no-print{display:none}.grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px}.card{min-height:0}}@media screen and (max-width:700px){.grid{grid-template-columns:1fr}}
</style></head><body>
<div class="no-print" style="margin-bottom:18px"><button onclick="window.print()">Print / Save as PDF</button></div>
<h1>{{ $curricula->name }} — Curriculum Summary</h1><p>Grade levels and assigned subjects</p>
<div class="grid">@forelse($gradeLevels as $gradeLevel)<section class="card"><h2>{{ $gradeLevel->gradeLevel?->grade_label ?? $gradeLevel->name }}</h2><div class="meta">{{ $gradeLevel->gradingSemester?->label ?? '—' }}@if($gradeLevel->cluster) · {{ $gradeLevel->cluster->name }}@endif</div>@if($gradeLevel->curriculumSubjects->isNotEmpty())<table><thead><tr><th>Subject Code</th><th>Subject Title</th><th>Type</th></tr></thead><tbody>@foreach($gradeLevel->curriculumSubjects->sortBy(fn($row) => $row->subject?->code) as $assignment)<tr><td>{{ $assignment->subject?->code ?? '—' }}</td><td>{{ $assignment->subject?->title ?? '—' }}</td><td>{{ $assignment->subject?->subjectType?->label ?? '—' }}</td></tr>@endforeach</tbody></table>@else<div class="empty">No assigned subjects.</div>@endif</section>@empty<p>No grade-level records are configured.</p>@endforelse</div>
</body></html>
